version: '3.8'

services:
  nmergeia:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nmerge-app
    restart: unless-stopped
    ports:
      - "8880:8880"
    environment:
      - PORT=8880
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./:/app
      - /app/node_modules
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 128M
    networks:
      - global-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  global-network:
    external: true
