server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Cabeceras HSTS y Seguridad Requeridas por Google Search Console
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;

    # Redirección 301 Canónica de Barras Finales (/faq/ -> /faq) para evitar URLs no evaluadas
    location ~ ^/(.+)/$ {
        return 301 https://$host/$1;
    }

    # Soporte para Single Page Application (SPA) Routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Desactivar cache para index.html para asegurar la ultima version
    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    }
}
